# Generated by Django 5.2.7 on 2025-10-15 15:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengaduan',
            old_name='deskripsi',
            new_name='isi_laporan',
        ),
        migrations.RemoveField(
            model_name='pengaduan',
            name='judul',
        ),
        migrations.RemoveField(
            model_name='pengaduan',
            name='pelapor',
        ),
        migrations.RemoveField(
            model_name='pengaduan',
            name='status',
        ),
        migrations.RemoveField(
            model_name='warga',
            name='tanggal_registrasi',
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='tanggal',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='warga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warga.warga'),
        ),
        migrations.AlterField(
            model_name='warga',
            name='alamat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='warga',
            name='nama_lengkap',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='warga',
            name='nik',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='warga',
            name='no_telepon',
            field=models.CharField(max_length=15),
        ),
    ]
